// src/generators/generate-react-component/template.ts
import { format } from "./../../utils";
import { ReactComponentOptions } from "./types";

export async function gnReactComponent(options: ReactComponentOptions) {
  const {
    memo,
    name: componentName,
    forwardRef,
    withProps = true,
    args = [],
    exportAsDefault = false,
    imports: incomingImports = [],
    renderContent = `    
      <>
        <h1>${componentName}</h1>
      </>
    `,
  } = options;

  const exportAsDefaultText = exportAsDefault ? "default" : "";

  const props = `${componentName}Props`;

  const propsDefinition = withProps
    ? `
    type ${props} = {
      // props go here
    };

  `
    : "";

  const imports: string[] = incomingImports;

  if (forwardRef || memo) {
    imports.push('import React from "react";');
  }

  let content = "";

  if (forwardRef) {
    if (forwardRef && args.length === 0) {
      args.push(`props: ${props}`, "ref: any");
    } else {
      args.push(`props: ${props}`);
    }

    // the return of the string should check if the component is memo or forwardRef
    // it could be both as well, so we need to check for both

    let exportStatement = "";

    if (memo && forwardRef) {
      exportStatement = `
        const ${componentName} = React.memo(React.forwardRef(_${componentName}));
      export ${exportAsDefaultText} ${componentName};`;
    } else if (memo) {
      exportStatement = `
        const ${componentName} = React.memo(_${componentName});
      export ${exportAsDefaultText} ${componentName};`;
    } else if (forwardRef) {
      exportStatement = `
        const ${componentName} = React.forwardRef(_${componentName});

      export ${exportAsDefaultText} ${componentName};`;
    }

    content = `function _${componentName}(${args.join(", ")}) {
      ${options.beforeRenderContent || ""}
      return (
        ${renderContent || ``}
      )
      }
      ${exportStatement}
      `;
  } else {
    args.push(withProps ? `props: ${props}` : "");
    content = `export ${exportAsDefaultText} function ${componentName}(${args.join(
      ", ",
    )}) {
      ${options.beforeRenderContent || ""}
      return (
        <>
          <h1>${componentName}</h1>
        </>
      )
    }
      `;
  }

  const importsString = imports.join("\n");

  const finalContent = `${importsString}\n${propsDefinition}${content}`;

  return await format.typescript(finalContent);
}

// src/generators/qwik/generate-qwik-component/template.ts
import { format } from "./../../../utils";
import { QwikComponentOptions } from "./types";

export async function gnQwikComponent(options: QwikComponentOptions) {
  //
  const {
    name: componentName,
    withProps = false,
    withSignal = false,
    withTask = false,
    withVisibleTask = false,
    imports: incomingImports = [],
    renderContent = `    
      <>
        <h1>${componentName}</h1>
      </>
    `,
  } = options;

  const props = `${componentName}Props`;

  const propsDefinition = withProps
    ? `
    export type ${props} = {
      // props go here
    };    
  `
    : "";

  const imports: string[] = incomingImports;

  let beforeContent = "";

  if (options.beforeRenderContent) {
    beforeContent = options.beforeRenderContent;
  }

  if (withSignal) {
    beforeContent += `
      const ${componentName}Sig = useSignal();
    `;

    imports.push(`import { useSignal } from '@builder.io/qwik';`);
  }

  if (withTask) {
    beforeContent += `
    useTask$(({ track }) => {
      // your logic goes here
    });
    `;

    imports.push(`import { useTask$ } from '@builder.io/qwik';`);
  }

  if (withVisibleTask) {
    beforeContent += `
    useVisibleTask$(({ track }) => {
      // your logic goes here
    });
    `;

    imports.push(`import { useVisibleTask$ } from '@builder.io/qwik';`);
  }

  imports.unshift("import { component$ } from '@builder.io/qwik';");

  const content = `export const ${componentName} = component$${
    withProps ? `<${props}>` : ""
  }((props) => {
    ${beforeContent}
    return (
      ${renderContent}
    )
  });
    `;

  const importsString = imports.join("\n");

  const finalContent = `${importsString}\n${propsDefinition}${content}`;

  return await format.typescript(finalContent);
}
